# Generated by Django 3.2.13 on 2022-04-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='ratingstar',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
